name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  IMG_LOCATION: ghcr.io/hgokduman/spf-flattener
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build the Docker image
      run: |
        docker build . --tag ${{env.IMG_LOCATION}}:latest
        docker push ${{env.IMG_LOCATION}}:latest
